### ISSUE TITLE
A Build error occur in Ubuntu 14.04

### ISSUE THREAD

**Issue by ghost** [01org/wayland-tracker#1]
Hello,

A build error occurred in wayland-tracker when I use cabal.
I can't understand Haskell at all, therefore I couldn't debug this.
Could you help me to build wayland-tracker?

I followed steps in README.md in Ubuntu 14.04. 

> osboxes@osboxes:~/Software/wayland-tracker$ ghc --version
> The Glorious Glasgow Haskell Compilation System, version 7.6.3
> osboxes@osboxes:~/Software/wayland-tracker$ cabal --version
> cabal-install version 1.16.0.2
> using version 1.16.0 of the Cabal library 
> 
> Building wayland-tracker-0.4.0.0...
> Preprocessing executable 'wayland-tracker' for wayland-tracker-0.4.0.0...
> [1 of 6] Compiling Wayland          ( cbits/Wayland.hs, dist/build/wayland-tracker/wayland-tracker-tmp/Wayland.o )
> [2 of 6] Compiling ParseWaylandXML  ( src/ParseWaylandXML.hs, dist/build/wayland-tracker/wayland-tracker-tmp/ParseWaylandXML.o )
> [3 of 6] Compiling Types            ( src/Types.hs, dist/build/wayland-tracker/wayland-tracker-tmp/Types.o )
> [4 of 6] Compiling Log              ( src/Log.hs, dist/build/wayland-tracker/wayland-tracker-tmp/Log.o )
> src/Log.hs:158:44:
>     Couldn't match expected type `AP.Config'
>                 with actual type`AP.NumberFormat -> AP.Config'
>     In the first argument of AP.encodePretty', namely `conf'
>     In the second argument of`($)', namely
>       `AP.encodePretty' conf smsg'
>     In a stmt of a 'do' block: BSL.hPut lh $ AP.encodePretty' conf smsg

**Comment by ipuustin** [comment]
Should be fixed now. A new aeson-pretty version was API-incompatible. We can go to latest aeson-pretty version as soon as stack supports it in the LTS releases.

**Comment by ipuustin** [comment]
@Jong7707 : please tell if it compiles now properly. :-)

**Comment by ghost** [comment]
@ipuustin It was fixed! Thanks for your help! 👍
